(ns examples.cldr-reduced)


(def
  data
  {"main"
   {"cs"
    {"dates"
     {"calendars"
      {"gregorian"
       {"months"
        {"format"
         {"abbreviated"
          {"9" "zář",
           "3" "bře",
           "4" "dub",
           "8" "srp",
           "7" "čvc",
           "5" "kvě",
           "12" "pro",
           "6" "čvn",
           "1" "led",
           "11" "lis",
           "2" "úno",
           "10" "říj"},
          "narrow"
          {"9" "9",
           "3" "3",
           "4" "4",
           "8" "8",
           "7" "7",
           "5" "5",
           "12" "12",
           "6" "6",
           "1" "1",
           "11" "11",
           "2" "2",
           "10" "10"},
          "wide"
          {"9" "září",
           "3" "března",
           "4" "dubna",
           "8" "srpna",
           "7" "července",
           "5" "května",
           "12" "prosince",
           "6" "června",
           "1" "ledna",
           "11" "listopadu",
           "2" "února",
           "10" "října"}},
         "stand-alone"
         {"abbreviated"
          {"9" "zář",
           "3" "bře",
           "4" "dub",
           "8" "srp",
           "7" "čvc",
           "5" "kvě",
           "12" "pro",
           "6" "čvn",
           "1" "led",
           "11" "lis",
           "2" "úno",
           "10" "říj"},
          "narrow"
          {"9" "9",
           "3" "3",
           "4" "4",
           "8" "8",
           "7" "7",
           "5" "5",
           "12" "12",
           "6" "6",
           "1" "1",
           "11" "11",
           "2" "2",
           "10" "10"},
          "wide"
          {"9" "září",
           "3" "březen",
           "4" "duben",
           "8" "srpen",
           "7" "červenec",
           "5" "květen",
           "12" "prosinec",
           "6" "červen",
           "1" "leden",
           "11" "listopad",
           "2" "únor",
           "10" "říjen"}}},
        "days"
        {"format"
         {"abbreviated"
          {"sun" "ne",
           "mon" "po",
           "tue" "út",
           "wed" "st",
           "thu" "čt",
           "fri" "pá",
           "sat" "so"},
          "narrow"
          {"sun" "N",
           "mon" "P",
           "tue" "Ú",
           "wed" "S",
           "thu" "Č",
           "fri" "P",
           "sat" "S"},
          "short"
          {"sun" "ne",
           "mon" "po",
           "tue" "út",
           "wed" "st",
           "thu" "čt",
           "fri" "pá",
           "sat" "so"},
          "wide"
          {"sun" "neděle",
           "mon" "pondělí",
           "tue" "úterý",
           "wed" "středa",
           "thu" "čtvrtek",
           "fri" "pátek",
           "sat" "sobota"}},
         "stand-alone"
         {"abbreviated"
          {"sun" "ne",
           "mon" "po",
           "tue" "út",
           "wed" "st",
           "thu" "čt",
           "fri" "pá",
           "sat" "so"},
          "narrow"
          {"sun" "N",
           "mon" "P",
           "tue" "Ú",
           "wed" "S",
           "thu" "Č",
           "fri" "P",
           "sat" "S"},
          "short"
          {"sun" "ne",
           "mon" "po",
           "tue" "út",
           "wed" "st",
           "thu" "čt",
           "fri" "pá",
           "sat" "so"},
          "wide"
          {"sun" "neděle",
           "mon" "pondělí",
           "tue" "úterý",
           "wed" "středa",
           "thu" "čtvrtek",
           "fri" "pátek",
           "sat" "sobota"}}}}}}},
    "en"
    {"dates"
     {"calendars"
      {"gregorian"
       {"months"
        {"format"
         {"abbreviated"
          {"9" "Sep",
           "3" "Mar",
           "4" "Apr",
           "8" "Aug",
           "7" "Jul",
           "5" "May",
           "12" "Dec",
           "6" "Jun",
           "1" "Jan",
           "11" "Nov",
           "2" "Feb",
           "10" "Oct"},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "September",
           "3" "March",
           "4" "April",
           "8" "August",
           "7" "July",
           "5" "May",
           "12" "December",
           "6" "June",
           "1" "January",
           "11" "November",
           "2" "February",
           "10" "October"}},
         "stand-alone"
         {"abbreviated"
          {"9" "Sep",
           "3" "Mar",
           "4" "Apr",
           "8" "Aug",
           "7" "Jul",
           "5" "May",
           "12" "Dec",
           "6" "Jun",
           "1" "Jan",
           "11" "Nov",
           "2" "Feb",
           "10" "Oct"},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "September",
           "3" "March",
           "4" "April",
           "8" "August",
           "7" "July",
           "5" "May",
           "12" "December",
           "6" "June",
           "1" "January",
           "11" "November",
           "2" "February",
           "10" "October"}}},
        "days"
        {"format"
         {"abbreviated"
          {"sun" "Sun",
           "mon" "Mon",
           "tue" "Tue",
           "wed" "Wed",
           "thu" "Thu",
           "fri" "Fri",
           "sat" "Sat"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "W",
           "thu" "T",
           "fri" "F",
           "sat" "S"},
          "short"
          {"sun" "Su",
           "mon" "Mo",
           "tue" "Tu",
           "wed" "We",
           "thu" "Th",
           "fri" "Fr",
           "sat" "Sa"},
          "wide"
          {"sun" "Sunday",
           "mon" "Monday",
           "tue" "Tuesday",
           "wed" "Wednesday",
           "thu" "Thursday",
           "fri" "Friday",
           "sat" "Saturday"}},
         "stand-alone"
         {"abbreviated"
          {"sun" "Sun",
           "mon" "Mon",
           "tue" "Tue",
           "wed" "Wed",
           "thu" "Thu",
           "fri" "Fri",
           "sat" "Sat"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "W",
           "thu" "T",
           "fri" "F",
           "sat" "S"},
          "short"
          {"sun" "Su",
           "mon" "Mo",
           "tue" "Tu",
           "wed" "We",
           "thu" "Th",
           "fri" "Fr",
           "sat" "Sa"},
          "wide"
          {"sun" "Sunday",
           "mon" "Monday",
           "tue" "Tuesday",
           "wed" "Wednesday",
           "thu" "Thursday",
           "fri" "Friday",
           "sat" "Saturday"}}}}}}},
    "en-GB"
    {"dates"
     {"calendars"
      {"gregorian"
       {"months"
        {"format"
         {"abbreviated"
          {"9" "Sept",
           "3" "Mar",
           "4" "Apr",
           "8" "Aug",
           "7" "Jul",
           "5" "May",
           "12" "Dec",
           "6" "Jun",
           "1" "Jan",
           "11" "Nov",
           "2" "Feb",
           "10" "Oct"},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "September",
           "3" "March",
           "4" "April",
           "8" "August",
           "7" "July",
           "5" "May",
           "12" "December",
           "6" "June",
           "1" "January",
           "11" "November",
           "2" "February",
           "10" "October"}},
         "stand-alone"
         {"abbreviated"
          {"9" "Sept",
           "3" "Mar",
           "4" "Apr",
           "8" "Aug",
           "7" "Jul",
           "5" "May",
           "12" "Dec",
           "6" "Jun",
           "1" "Jan",
           "11" "Nov",
           "2" "Feb",
           "10" "Oct"},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "September",
           "3" "March",
           "4" "April",
           "8" "August",
           "7" "July",
           "5" "May",
           "12" "December",
           "6" "June",
           "1" "January",
           "11" "November",
           "2" "February",
           "10" "October"}}},
        "days"
        {"format"
         {"abbreviated"
          {"sun" "Sun",
           "mon" "Mon",
           "tue" "Tue",
           "wed" "Wed",
           "thu" "Thu",
           "fri" "Fri",
           "sat" "Sat"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "W",
           "thu" "T",
           "fri" "F",
           "sat" "S"},
          "short"
          {"sun" "Su",
           "mon" "Mo",
           "tue" "Tu",
           "wed" "We",
           "thu" "Th",
           "fri" "Fr",
           "sat" "Sa"},
          "wide"
          {"sun" "Sunday",
           "mon" "Monday",
           "tue" "Tuesday",
           "wed" "Wednesday",
           "thu" "Thursday",
           "fri" "Friday",
           "sat" "Saturday"}},
         "stand-alone"
         {"abbreviated"
          {"sun" "Sun",
           "mon" "Mon",
           "tue" "Tue",
           "wed" "Wed",
           "thu" "Thu",
           "fri" "Fri",
           "sat" "Sat"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "W",
           "thu" "T",
           "fri" "F",
           "sat" "S"},
          "short"
          {"sun" "Su",
           "mon" "Mo",
           "tue" "Tu",
           "wed" "We",
           "thu" "Th",
           "fri" "Fr",
           "sat" "Sa"},
          "wide"
          {"sun" "Sunday",
           "mon" "Monday",
           "tue" "Tuesday",
           "wed" "Wednesday",
           "thu" "Thursday",
           "fri" "Friday",
           "sat" "Saturday"}}}}}}},
    "sv"
    {"dates"
     {"calendars"
      {"gregorian"
       {"months"
        {"format"
         {"abbreviated"
          {"9" "sep.",
           "3" "mars",
           "4" "apr.",
           "8" "aug.",
           "7" "juli",
           "5" "maj",
           "12" "dec.",
           "6" "juni",
           "1" "jan.",
           "11" "nov.",
           "2" "feb.",
           "10" "okt."},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "september",
           "3" "mars",
           "4" "april",
           "8" "augusti",
           "7" "juli",
           "5" "maj",
           "12" "december",
           "6" "juni",
           "1" "januari",
           "11" "november",
           "2" "februari",
           "10" "oktober"}},
         "stand-alone"
         {"abbreviated"
          {"9" "sep.",
           "3" "mars",
           "4" "apr.",
           "8" "aug.",
           "7" "juli",
           "5" "maj",
           "12" "dec.",
           "6" "juni",
           "1" "jan.",
           "11" "nov.",
           "2" "feb.",
           "10" "okt."},
          "narrow"
          {"9" "S",
           "3" "M",
           "4" "A",
           "8" "A",
           "7" "J",
           "5" "M",
           "12" "D",
           "6" "J",
           "1" "J",
           "11" "N",
           "2" "F",
           "10" "O"},
          "wide"
          {"9" "september",
           "3" "mars",
           "4" "april",
           "8" "augusti",
           "7" "juli",
           "5" "maj",
           "12" "december",
           "6" "juni",
           "1" "januari",
           "11" "november",
           "2" "februari",
           "10" "oktober"}}},
        "days"
        {"format"
         {"abbreviated"
          {"sun" "sön",
           "mon" "mån",
           "tue" "tis",
           "wed" "ons",
           "thu" "tors",
           "fri" "fre",
           "sat" "lör"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "O",
           "thu" "T",
           "fri" "F",
           "sat" "L"},
          "short"
          {"sun" "sö",
           "mon" "må",
           "tue" "ti",
           "wed" "on",
           "thu" "to",
           "fri" "fr",
           "sat" "lö"},
          "wide"
          {"sun" "söndag",
           "mon" "måndag",
           "tue" "tisdag",
           "wed" "onsdag",
           "thu" "torsdag",
           "fri" "fredag",
           "sat" "lördag"}},
         "stand-alone"
         {"abbreviated"
          {"sun" "sön",
           "mon" "mån",
           "tue" "tis",
           "wed" "ons",
           "thu" "tors",
           "fri" "fre",
           "sat" "lör"},
          "narrow"
          {"sun" "S",
           "mon" "M",
           "tue" "T",
           "wed" "O",
           "thu" "T",
           "fri" "F",
           "sat" "L"},
          "short"
          {"sun" "sö",
           "mon" "må",
           "tue" "ti",
           "wed" "on",
           "thu" "to",
           "fri" "fr",
           "sat" "lö"},
          "wide"
          {"sun" "söndag",
           "mon" "måndag",
           "tue" "tisdag",
           "wed" "onsdag",
           "thu" "torsdag",
           "fri" "fredag",
           "sat" "lördag"}}}}}}}}})

